apiVersion: v1
kind: Service
metadata:
  name: config-node-port
spec:
  type: NodePort
  ports:
    - port: 8080 # port for other pods to communicate
      targetPort: 8080 # container-port
      nodePort: 30080 # exposed beyond k8s cluster to access
#    - port: 8888
#      targetPort: 8888
#      nodePort: 30088
  selector:
    component: config