services:
  config-server:
    build: config-server
    env_file:
      - .env
    command: ["--spring.rabbitmq.username=${RABBITMQ_USER}", "--spring.rabbitmq.password=${RABBITMQ_PASSWORD}"]
    depends_on:
      rabbit-mq:
        condition: service_healthy
        restart: true
    healthcheck:
      test: [ "CMD-SHELL", "netstat -nl | grep 8888"]
      interval: 15s
      timeout: 5s
      retries: 3
    deploy:
      mode: replicated
      replicas: 2

  config-client1:
    build: limits-service
    env_file:
      - .env
    environment:
      - spring.rabbitmq.username=${RABBITMQ_USER}
      - spring.rabbitmq.password=${RABBITMQ_PASSWORD}
    depends_on:
      config-server:
        condition: service_healthy
        restart: true
      rabbit-mq:
        condition: service_healthy
        restart: true
    ports:
      - "8080:8080"

  config-client2:
    build: limits-service
    env_file:
      - .env
    environment:
      - spring.rabbitmq.username=${RABBITMQ_USER}
      - spring.rabbitmq.password=${RABBITMQ_PASSWORD}
    depends_on:
      config-server:
        condition: service_healthy
        restart: true
      rabbit-mq:
        condition: service_healthy
        restart: true
    ports:
      - "8081:8080"

  rabbit-mq:
    image: bitnami/rabbitmq
    env_file:
      - .env
    entrypoint: sh -c "
      nohup /opt/bitnami/scripts/rabbitmq/entrypoint.sh /opt/bitnami/scripts/rabbitmq/run.sh 
      & echo 'Waiting to create user...' 
      && until sleep 25s && rabbitmqctl list_users | grep ${RABBITMQ_USER} || rabbitmqctl add_user ${RABBITMQ_USER} ${RABBITMQ_PASSWORD}; 
      do echo 'Try again'; 
      sleep 5; done 
      && rabbitmqctl set_user_tags ${RABBITMQ_USER} administrator 
      && rabbitmqctl set_permissions -p / ${RABBITMQ_USER} '.*' '.*' '.*'
      && trap 'rabbitmqctl stop' TERM
      && wait $(pgrep -f rabbitmq-server)"
    ports:
      - "15672:15672"
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl list_permissions | grep ${RABBITMQ_USER}"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s