# Config-server details for Lower / Non-Prod Environments
spring:
  config:
    # Config-server URL to be placed on env specific profile if exists, else will hit dual calls
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      username: ${CONFIG_USER:admin}
      password: ${CONFIG_PASS:admin}
  rabbitmq:
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 8080

logging:
  level:
    org.edu.abhi.limitsservice:
      configuration: DEBUG

limits-service:
  users:
    - username: user
      password: pass
      roles: USER
    - username: admin
      password: admin
      roles: USER, ADMIN
    - username: anonymous
      password: pass
      roles: