# Config-server details for Lower / Non-Prod Environments
spring:
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888} # Only to be placed on env specific profile if exists, else will hit dual calls

server:
  port: 8080

logging:
  level:
    org:
      edu:
        abhi:
          limitsservice:
            config: debug