spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhisheksarkar30/server-configs
          default-label: main
          username: does-not-matter # for private repo
          password: override-on-config # for private repo
          search-paths: limits-service
          clone-on-start: true
    bus:
      enabled: false
server:
  port: 8888
