name: Pull & Deploy reusable workflow
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      vm-label:
        required: true
        type: string

jobs:
  pull-deploy:
    runs-on: [self-hosted, ${{ inputs.vm-label }}] # self-hosted AND {{vm-label}}
    steps:
      - name: Download docker-compose file
        run: curl "https://raw.githubusercontent.com/abhisheksarkar30/spring-cloud-config/docker-compose/docker-compose.yml" > docker-compose.yml
      - name: Download .env file
        run: curl "https://raw.githubusercontent.com/abhisheksarkar30/spring-cloud-config/docker-compose/.env" > .env
      - name: Down already created docker-compose containers
        run: docker-compose down
      - name: Up docker-compose container with freshly pulled images
        run: docker-compose up -d --pull always
