name: Test & deploy docker-compose app
on:
  workflow_dispatch:
  push:
    branches:
      - docker-compose # branch name for compose app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

#      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#      - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
#      - run: docker run -e CI=true cygnetops/react-test npm test

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test config-server
        run: mvn test -f ./config-server/pom.xml
      - name: Package config-server
        run: mvn jar:jar -f ./config-server/pom.xml

      - name: Test limits-service
        run: mvn test -f ./limits-service/pom.xml
      - name: Package limits-service
        run: mvn jar:jar -f ./limits-service/pom.xml

      - name: docker-compose build
      - run: docker-compose build --push
