name: Build, Test & Deploy workflow
on:
  workflow_dispatch:
  push:
    branches:
      - docker-compose # branch name for compose app
    paths-ignore:
      - '**/*.md'
      - '**/.gitignore'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Compile, test & Package config-server
        run: mvn package -f ./config-server/pom.xml

      - name: Compile, test & Package limits-service
        run: mvn package -f ./limits-service/pom.xml

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker-compose build
        run: docker compose build --push
        
  call-pull-deploy-workflow:
    needs: build-push
    strategy:
      matrix:
        target-vms: [ rog-vm, desk-vm ]
    uses: ./.github/workflows/actions-deploy.yml
    with:
      target-vm: ${{ matrix.target-vms }} # will create separate jobs, one for each of the labels in {{ target-vms }}