name: Pull & Deploy reusable workflow
on:
  workflow_dispatch:
    inputs:
      target-vm:
        description: target vm-label
        required: true
        type: string
  workflow_call:
    inputs:
      target-vm:
        required: true
        type: string

jobs:
  pull-deploy:
    runs-on:
      labels:
        - ${{ inputs.target-vm }}
    steps:
      - name: Download Pod file
        run: curl "https://raw.githubusercontent.com/abhisheksarkar30/spring-cloud-config/main/config-pod.yaml" > config-pod.yaml
      - name: Download NodePort file
        run: curl "https://raw.githubusercontent.com/abhisheksarkar30/spring-cloud-config/main/config-node-port.yaml" > config-node-port.yaml
      - name: Recreate existing Pod config
        run: kubectl delete -f config-pod.yaml && kubectl apply -f config-pod.yaml
      - name: Recreate existing NodePort config
        run: kubectl delete -f config-node-port.yaml && kubectl apply -f config-node-port.yaml
